# A string used to distinguish different projects on the same host. Defaults to the working directory name when running `supabase init`.
project_id = "theberman"

[functions.create-admin-user]
verify_jwt = false
